FROM node:18.19.0 as build

WORKDIR /app

COPY package.json package-lock.json angular.json /

RUN npm install -g @angular/cli
RUN npm install

COPY . .

RUN ng build --configuration=production

FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/memo/browser /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]